src/Decoder/HtmlDecoder.php
src/Processor/CodeHighlightProcessor.php
src/Resources/config/services.yaml
src/Service/Parsedown.php

La coloration syntaxique est appliqué comme un post-processor à tout les blocs `<code highlight="xxx">` dans le contenu.
Avantages : 
- Décorrélé des décodeurs (le même code s'applique que le contenu ai été produit depuis un fichier markdown ou html).
- L'utilisateur peu changer de décodeur Markdown ou créer des décodeur custom : il bénéficiera quand même de la coloration syntaxique.
- Facilement désactivable.
- Gère automatiquement les cas à la marge (comme un bloque code inséré directement en HTML dans un fichier markdown).

Move synthax highlighting in a common Processor

---

src/ContentManager.php
src/Processor/CodeHighlightProcessor.php
src/Processor/LastModifiedProcessor.php
src/Resources/config/services.php
src/Serializer/Normalizer/SkippingInstantiatedObjectDenormalizer.php

Ex without:
```
In DateTimeNormalizer.php line 101:
DateTimeImmutable::__construct() expects parameter 1 to be string, object given
```
Due to the `LastModifiedProcessor` returning an already instantiated `\DateTime` object.
This adds more flexibility to the processors.

Allow processors to hydrate objects

---

doc/loading-content.md
src/ContentManager.php
src/Twig/ContentRuntime.php
tests/Unit/ContentManagerTest.php

--- 
```php
$activeUsers = $this->manager->getContents(User::class, null, 'active');
```
```php
$articles = $this->manager->getContents(Article::class, null, ['category' => 'Infra']);
```
```php
$myDrafts = $this->manager->getContents(Article::class, null, ['author' => 'ogi', 'draft' => true]);
```
Le sorting bénéficie aussi de cet amélioration : 
```php
// Sort by author and then by date:
$articles = $this->manager->getContents(Article::class, ['author' => true, 'date' => false]);
```
```php
$articlesAboutMobile = $this->manager->getContents(
Article::class,
null,
fn (Article $article): bool => in_array('mobile', $article->tags)
);
```

Provide a filter option for getContents + allow multiple sort keys

---

composer.json
src/Processor/HtmlIdProcessor.php
src/Resources/config/services.php

See https://symfony.com/doc/current/components/string.html
The component is already shipped in most installs, as it's a transitive dependency of console & property-info. So let's rely on its shoulders.
It supports transliteration and locale specific transformations.

Rely on String component for anchor slugs

---

src/Provider/LocalFilesystemProvider.php
tests/Unit/Provider/LocalFilesystemProviderTest.php

Given the following definition:
```yaml
content:
providers:
App\Model\Recipe:
path: '%kernel.project_dir%/content/'
excludes:
- docs
```
it will only ignore a `%kernel.project_dir%/content/docs` file, but not the whole `%kernel.project_dir%/content/docs` directory, as it internally uses Symfony `Finder::path/notPath()` which expects regex for the whole filepath.
However we are internally allowing globs for a better experience. As a consequence, the proper way to exclude everything inside a dir is to use `docs/**` as an exclude pattern.
DX can be improved though, by considering an explicit dir (`docs/`, with trailing `/`) and converting it to `docs/**` internally:
```yaml
content:
providers:
App\Model\Recipe:
path: '%kernel.project_dir%/content/'
excludes:
- docs/ # => /docs/**
```

Improve local fs provider patterns DX for dirs

---

doc/app/config/packages/stenope.yaml
phpstan.neon.dist
src/Provider/LocalFilesystemProvider.php
tests/Unit/Provider/LocalFilesystemProviderTest.php

Improves drastically the performances when excluding consequent directories like `node_modules` or `vendor` for instance, 
by relying on `Finder::exclude` rather than `notPath` whenever we detect an explicit directory exclusion (the Stenope doc app is affected).
See https://blackfire.io/profiles/compare/21f2db19-e74e-4d09-9500-bc3624a4754f/graph
(the time is not really relevant for the comparison, as the profile without this patch is erroneous, and rendering time would rather be something like between 2 and 3 secs. However, see the saved method calls.)
I'm a bit annoyed with the commented test-case, but there is a way to circumvent for particular case as explained in the comment (until there is a fix in Symfony Finder allowing to properly exclude only the specified dirs).
But I feel the …

Improve local fs perfs with excluded dirs

---

doc/app/composer.json
doc/app/composer.lock

using Composer path repositories

Always use the current Stenope version to build docs

---

doc/route-options.md
doc/troubleshooting.md

as those are the future and are way more easy to write multiline since it's pure PHP syntax and not mixed with docblocks.

[Doc] Use PHP 8 attributes for examples

---

src/Builder.php
src/Command/BuildCommand.php
src/ContentManager.php
src/Exception/ContentNotFoundException.php
src/Exception/ExceptionInterface.php

Use-case:
I want to be able to build the static site in a "Preview" job, even if there are missing content pages detected, so I can still deploy a preview of the current PR. This new flag allows it.
However, in another "CI / Tests" job, I do not add this flag, so I still have a failing check on my PR to inspect and be aware there is probably an issue.
poke @benji07 @maximecolin

Add a --ignore-content-not-found flag to build command

---

config/services.php
src/Processor/AssetsProcessor.php
src/Service/AssetUtils.php

So we can properly link to local assets (with URLs resolved by the Asset component), like PDFs & other files.

Expand assets URLs processing to links

---

config/services.php
src/Builder.php
src/EventListener/SitemapListener.php
src/Routing/RouteInfo.php
src/Routing/RouteInfoCollection.php
src/Routing/UrlGenerator.php

Even if a route is explicitly marked as ignored by Stenope in its
routing options, if the route was used to generate an URL inside a
non-ignored route, it'll still be part of the build.
This is problematic, even more when the route is only used to generate
an URL to an external resource.
Let's properly ignore such routes in the UrlGenerator.

Do ignore routes even if generated during build

---

src/Processor/LastModifiedProcessor.php

to only add the file last modification date if the property is absent from content metadata (so we can keep explicit `null` values)
Actually, I'm not even sure this processor is relevant since it in most cases always matches the last deployment date (last time the repository was cloned).

Fix LastModifiedProcessor

---

src/Service/AssetUtils.php
tests/Unit/Service/AssetsUtilsTest.php

Otherwise it attempts to process links like `tel:XXX`, `mailto:XXX` as assets and might prepend the base url or host.

Fix assets processor for schemes like mailto:

---

doc/app/Makefile
src/Service/AssetUtils.php
tests/Unit/Service/AssetsUtilsTest.php

Currently, anchors links are broken on the docs (https://stenopephp.github.io/Stenope/loading-content/ => click on any title) and redirects to the base URL.
We should not attempt to resolve such links neither with the assets processor.

Fix doc anchors: Asset processor should not process anchors

---

config/services.php
doc/app/composer.lock
doc/app/config/packages/dev/monolog.yaml
doc/app/config/packages/prod/monolog.yaml
doc/app/config/services.yaml
doc/app/src/Model/Page.php
doc/app/src/Processor/DefaultTocProcessor.php
doc/app/templates/doc/index.html.twig
src/Processor/TableOfContentProcessor.php
tests/Integration/BuildTest.php
tests/Integration/TableOfContentTest.php
tests/Unit/TableOfContent/CrawlerTableOfContentGeneratorTest.php
tests/fixtures/app/content/authors/tom32i.md
tests/fixtures/app/content/recipes/ogito.md
tests/fixtures/app/content/recipes/tomiritsu.md
tests/fixtures/app/src/Model/Recipe.php
tests/fixtures/app/templates/recipe/show.html.twig

Fixes the TOC processor in case there is no content property in the expected model.
Additionally, I suggest multiple changes to enhance the default integration:
- change the wired min depth to h2, since most of the time, h1 are unique, on top of the page and thus useless in a TOC
- make the TOC generation opt-in, so it won't be generated for every contents by default, but can be enabled using `tableOfContent: true` or an int value (see below). It can also be easily enabled automatically using another processor for some types, as done for the documentation here. `false` can be used in such cases to explicitly disable it.
- allow to configure the max depth per content, using an int value for the `tableOfContent` metadata.
These changes aim to provide better defaults so we can keep this …

Fix & enhance the TOC processor

---

composer.json
config/services.php
config/tags.php
doc/app/assets/styles/_admonitions.scss
doc/app/assets/styles/_variables.scss
doc/app/assets/styles/style.scss
doc/cli.md
doc/loading-content.md
doc/twig.md
src/Command/DebugCommand.php
src/ContentManager.php
src/DependencyInjection/StenopeExtension.php
src/ExpressionLanguage/Expression.php
src/ExpressionLanguage/ExpressionLanguage.php
src/ExpressionLanguage/ExpressionLanguageProvider.php
src/ExpressionLanguage/exprs.php
src/Twig/ContentExtension.php
tests/Integration/Command/DebugCommandTest.php
tests/Unit/ContentManagerTest.php
tests/Unit/ExpressionLanguage/ExpressionTest.php

Fixes #99. A bit more verbose, but waaay more powerful and extensible.
```bash
See https://symfony.com/doc/current/components/expression_language/syntax.html
The current item is referred using "data", "d" or "_":
php bin/console debug:stenope:content "App\Model\Author" --filter=data.active
php bin/console debug:stenope:content "App\Model\Author" --filter=d.active
php bin/console debug:stenope:content "App\Model\Author" --filter=_.active
Negation:
php bin/console debug:stenope:content "App\Model\Author" --filter='not d.active'
php bin/console debug:stenope:content "App\Model\Author" --filter='!d.active'
Contains:
php bin/console debug:stenope:content "App\Model\Article" --filter='contains(_.slug, "symfony")'
You can also use multiple filters at once:
php bin/console debug:stenope:content …
```

Use Symfony's ExpressionLanguage component for filters

---

config/services.php
phpstan.neon.dist
src/Content.php
src/Processor/LastModifiedProcessor.php
src/Provider/LocalFilesystemProvider.php
src/Service/Git/LastModifiedFetcher.php
tests/Integration/Command/DebugCommandTest.php
tests/Unit/Processor/LastModifiedProcessorTest.php
tests/Unit/Service/Git/LastModifiedFetcherTest.php
tests/fixtures/Unit/Service/Git/bin/git.php

Fixes #98
⚠️ small BC inside => use `\DateTimeInterface` or `\DateTimeImmutable` on your model objects, since this processor now returns a `DateTimeImmutable` now (before was `\DateTime`).

Use git last commit date for a file as default last modified date

---

doc/loading-content.md
doc/twig.md
src/ContentManager.php
tests/Unit/ContentManagerTest.php

I suggest to remove this syntax:
```php
$users = $contentManager->getContents(User::class, null, 'active');
```
in favor of expressions:
```php
$users = $contentManager->getContents(User::class, null, '_.active');
```
since:
- it's not much more complex to write
- it allows to enable first-class support for expressions as filters, removing the need to create an `Expression` instance with `expr`/ `exprOr`, and expressions are way more powerful:
```diff
-$users = $contentManager->getContents(User::class, null, expr('_.active'));
+$users = $contentManager->getContents(User::class, null, '_.active');
```
- we do not seem to use this syntax since the  begining, but rather use:
```php
$users = $contentManager->getContents(User::class, null, ['active' => true]);
```
WDYT?

Remove property filter as string to promote expressions

---

config/services.php
doc/app/src/Controller/DocController.php
doc/loading-content.md
doc/twig.md
src/Behaviour/ContentManagerAwareInterface.php
src/Behaviour/ContentManagerAwareTrait.php
src/Command/DebugCommand.php
src/ContentManager.php
src/ContentManagerInterface.php
src/HttpKernel/Controller/ArgumentResolver/ContentArgumentResolver.php
src/ReverseContent/Context.php
src/Twig/ContentRuntime.php
tests/Unit/HttpKernel/Controller/ArgumentResolver/ContentArgumentResolverTest.php
tests/Unit/Processor/ResolveContentLinksProcessorTest.php

first need: allowing decoration of the whole content manager
Note: For existing apps, in order for decoration to work as expected, any `ContentManager` typehints and DI injection must be replaced to use the `ContentManagerInterface`, otherwise, your custom code might not be called in every context.
--- 
⚠️ BC Break: 
The `ContentManagerAwareInterface` now uses `ContentManagerInterface` as its typehints instead of `ContentManager`. That should not be an issue if you use the `ContentManagerAwareTrait` though.

Add a ContentManagerInterface

---

composer.json
doc/app/composer.json
src/Builder.php
tests/Integration/BuildTest.php
tests/fixtures/app/config/bundles.php
tests/fixtures/app/config/config.yaml
tests/fixtures/app/src/Controller/NoIndexController.php
tests/fixtures/app/templates/base.html.twig
tests/fixtures/app/templates/noindex/with.html.twig
tests/fixtures/app/templates/noindex/without.html.twig

Warn user about HTTP No-Index headers

---

config/services.php
src/Command/DebugCommand.php
src/DependencyInjection/StenopeExtension.php

If not provided in command line, ask interactively the user:
It's a first step to #105, since it registers the known types in the command.

[Debug] Interactively ask for class

---

src/ContentManagerInterface.php

See https://arnaud.le-blanc.net/post/phpstan-generics.html#bounds
With this, PhpStan properly detects the return type of `ContentManagerInterface::getContent(Foo::class, 'foo')` is of type `Foo` and not just `object`

[PhpStan] Fix @template boundaries

---

src/Highlighter/Prism.php

Fixes:
```bash
In Process.php line 1292:
[Exception]
Cannot rewind a generator that was already run
Exception trace:
at app/vendor/symfony/process/Process.php:1292
IteratorIterator->rewind() at app/vendor/symfony/process/Process.php:1292
Symfony\Component\Process\Process->getDescriptors() at app/vendor/symfony/process/Process.php:307
Symfony\Component\Process\Process->start() at app/vendor/stenope/stenope/src/Highlighter/Prism.php:44
```

[Prism] Reset server on kernel.terminate

---

src/Highlighter/Prism.php

In case a page takes time to build and contains multiple highlight calls,
the time elapsed between 2 calls might be too long and the process might timeout (for instance, if there is a large amount of images to resize in the page).
Instead of using a global timeout for the process, let's use an idle timeout (time without any output) between each highlight call and reset it after getting a response from the Node process.

[Prism] Fix process timeouts between highlight calls for long building pages

---

src/Command/BuildCommand.php
src/Command/DebugCommand.php

fixing a 6.1 deprecation about Command::$defaultName usage

Use AsCommand PHP 8 attribute

---

doc/app/config/packages/routing.yaml
doc/app/config/services.yaml

Reverting two piece of configuration that were removed (by mistake?) on [commit d090c99](https://github.com/StenopePHP/Stenope/commit/d090c99c868a0247969c103263f9af2bb478695c#).
The routing config causes the link to break on [stenopephp.github.io/stenope/](https://stenopephp.github.io/Stenope/)

Fixing default URL root for documentation build.

---

src/Behaviour/HtmlCrawlerManagerInterface.php
src/Processor/HtmlIdProcessor.php
src/Service/NaiveHtmlCrawlerManager.php
src/Service/Parsedown.php
src/Service/SharedHtmlCrawlerManager.php
tests/Unit/Processor/ResolveContentLinksProcessorTest.php
tests/Unit/Service/HtmlCrawlerManagerTest.php

Remove extra body tags from processed contents

---

src/Builder.php
tests/Integration/BuildTest.php
tests/fixtures/app/content/recipes/stockholm mule.md

so that the file path does not contains URL-encoded chars anymore, 
which would prevent serving them properly.
I have an application that includes some PDFs files rendered through a controller, where the original file might contain spaces that would be encoded in the URL (`%20`). Without this patch, the resulting file contains the encoded chars (e.g: `recipes/stockholm%20mule.pdf`). So once build statically, it cannot be served as expected. 
Bonus: 🍸

[Builder] Decode URLs before dumping to file
